### ISSUE TITLE
'COO' object has no attribute 'format'

### ISSUE THREAD

**Issue by YuanbinLiu** [arosen93/QMOF#24]
Dear authors,

When I run soap_matrix_generator.py, there is an error as follows. 

**Traceback (most recent call last):
  File "soap_matrix_generator.py", line 59, in <module>
    save_npz(soap_filename, soap_matrix)
  File "/home/liu/.local/lib/python3.6/site-packages/scipy/sparse/_matrix_io.py", line 56, in save_npz
    if matrix.format in ('csc', 'csr', 'bsr'):
AttributeError: 'COO' object has no attribute 'format'**

Is something wrong with 'dscribe' or 'scipy.saprse'?

**Comment by arosen93** [comment]
Hi @YuanbinLiu. Yes, this looks to be a breaking change starting with dscribe 1.0.0. They changed the way they format their sparse matrices, as described [here](https://singroup.github.io/dscribe/latest/tutorials/sparse.html). Fortunately, the fix is very simple! Simply change `from scipy.sparse import save_npz` with `from sparse import save_npz`. I've updated the scripts.
